/*
 * FinVerse Article Data
 * Real, substantive market structure analysis articles.
 * Categories: Structure, Macro, Psychology
 * All content authored by Toufic Mourtada — The Trader Alchemist
 */

export type ArticleCategory = "Structure" | "Macro" | "Psychology";

export interface Article {
  slug: string;
  title: string;
  excerpt: string;
  category: ArticleCategory;
  date: string;
  readTime: string;
  thumbnail: string;
  content: {
    intro: string;
    htfAnalysis: string;
    intradayNarrative: string;
    structuralConfirmation: string;
    riskArchitecture: string;
    lessons: string;
  };
}

const CHART_1 = "https://private-us-east-1.manuscdn.com/sessionFile/feCh4CM4AAJJxZhdsCxOxr/sandbox/uxzclZHkFL47M3ji1YrWWH-img-1_1771418982000_na1fn_Y2hhcnQtdGh1bWJuYWlsLTE.png?x-oss-process=image/resize,w_1920,h_1920/format,webp/quality,q_80&Expires=1798761600&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wcml2YXRlLXVzLWVhc3QtMS5tYW51c2Nkbi5jb20vc2Vzc2lvbkZpbGUvZmVDaDRDTTRBQUpKeFpoZHNDeE94ci9zYW5kYm94L3V4emNsWkhrRkw0N00zamkxWXJXV0gtaW1nLTFfMTc3MTQxODk4MjAwMF9uYTFmbl9ZMmhoY25RdGRHaDFiV0p1WVdsc0xURS5wbmc~eC1vc3MtcHJvY2Vzcz1pbWFnZS9yZXNpemUsd18xOTIwLGhfMTkyMC9mb3JtYXQsd2VicC9xdWFsaXR5LHFfODAiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3OTg3NjE2MDB9fX1dfQ__&Key-Pair-Id=K2HSFNDJXOU9YS&Signature=UeKwZJdnaQA2YX1p5f0NuTBnliMvhCHPgCXJBdrjo6as1eP746deo3YCtYncOmD45qsKh5tpFJXxV4oTpskU-Gw726A4Z49nlrvDIUlipnhrND4hZAyVf6jMmx-H1J9yYrIQKCTNTWprYelP-3-zU7A2kf7s4bPAaJTZvLvQAC8hlC7PQlfRUec1dL52h0RGgpDFdUgBe6jhhgix0LDInofZCoZ~HpONAtdqygmHMeCLQsuK~-ePD~od9PeCt2rK~guDifCPQHtLvBK2mIxJ5ZPp6zVnmHuyY66V-24JuAbUtdXD-iMTkLm6q0tl0uefYARIlSYzV-SPmi52qmDk9w__";
const CHART_2 = "https://private-us-east-1.manuscdn.com/sessionFile/feCh4CM4AAJJxZhdsCxOxr/sandbox/uxzclZHkFL47M3ji1YrWWH-img-2_1771418968000_na1fn_Y2hhcnQtdGh1bWJuYWlsLTI.png?x-oss-process=image/resize,w_1920,h_1920/format,webp/quality,q_80&Expires=1798761600&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wcml2YXRlLXVzLWVhc3QtMS5tYW51c2Nkbi5jb20vc2Vzc2lvbkZpbGUvZmVDaDRDTTRBQUpKeFpoZHNDeE94ci9zYW5kYm94L3V4emNsWkhrRkw0N00zamkxWXJXV0gtaW1nLTJfMTc3MTQxODk2ODAwMF9uYTFmbl9ZMmhoY25RdGRHaDFiV0p1WVdsc0xUSS5wbmc~eC1vc3MtcHJvY2Vzcz1pbWFnZS9yZXNpemUsd18xOTIwLGhfMTkyMC9mb3JtYXQsd2VicC9xdWFsaXR5LHFfODAiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3OTg3NjE2MDB9fX1dfQ__&Key-Pair-Id=K2HSFNDJXOU9YS&Signature=vzm4UryREstb-hVLv6q5P-5bGxtP9hGx9nAqVMi0dKfp8RRHAHIYJxL34nMXNvbYMvCvkrU3agE0OmQQkxTgYiyjjFnrBQ02n8RCKHZtQVlLKguROdRgPpZxw2NZVX6Br6~txLXfgebqVQsHM~VTp800e0nlGqp5KQnA0plqYVcGAIjgMuTPOejEllkPkQta-VtffZzxdujq9uLXb3YpCej1CY90TsD~qrdMcv0tRUN-~7pOl6WgU3CqRx-GX1ejMzSIg0EoRK2VTT2V3TxuSAuf4C0zPeraQZJ1aCK-a~YdPa4nvYSZRBFlSAq2HhGHeZ8FKUTTIu3k6e1Vzm9wFg__";
const CHART_3 = "https://private-us-east-1.manuscdn.com/sessionFile/feCh4CM4AAJJxZhdsCxOxr/sandbox/uxzclZHkFL47M3ji1YrWWH-img-3_1771418968000_na1fn_Y2hhcnQtdGh1bWJuYWlsLTM.png?x-oss-process=image/resize,w_1920,h_1920/format,webp/quality,q_80&Expires=1798761600&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wcml2YXRlLXVzLWVhc3QtMS5tYW51c2Nkbi5jb20vc2Vzc2lvbkZpbGUvZmVDaDRDTTRBQUpKeFpoZHNDeE94ci9zYW5kYm94L3V4emNsWkhrRkw0N00zamkxWXJXV0gtaW1nLTNfMTc3MTQxODk2ODAwMF9uYTFmbl9ZMmhoY25RdGRHaDFiV0p1WVdsc0xUTS5wbmc~eC1vc3MtcHJvY2Vzcz1pbWFnZS9yZXNpemUsd18xOTIwLGhfMTkyMC9mb3JtYXQsd2VicC9xdWFsaXR5LHFfODAiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3OTg3NjE2MDB9fX1dfQ__&Key-Pair-Id=K2HSFNDJXOU9YS&Signature=N7HBv~knS8RuXKBXEYgzrgdxQ2E8SPkZjBr9p-VeskG8vwz8DdmYLnKc0U8xbKZXGKb4-1nvev7GanmfDsvXNJdAA45v6EZIgn-F9siD2mliEk13YtUziyVc0CtwJV0CTvPpUm-UuWM3LSvy~8gBegw1aZPPZ0PWpWRuMLbsyJxlRRKK4adGoWL7Z~rXbCwqmQ1k62aQ-n5VvoEjQ3SbgUlep~eI8ErFDtrtdrY6wG41geqkSvOEeIwKxt3Xc3zbNEj6gO5fIiXTIP8woLfmXjtOkDziAPO8fwl06bstbZVB35lEebeLBBti9Zbi-D0dUGtxkfOpUR62az5YkrnrlA__";

export const articles: Article[] = [
  {
    slug: "how-to-choose-a-broker-for-smc-execution",
    title: "How to Choose a Broker for SMC Execution — What Actually Matters",
    excerpt: "Most traders pick a broker based on spreads alone. That is the wrong variable. This breakdown covers execution quality, order routing, and platform requirements that determine whether your SMC entries survive contact with a live account.",
    category: "Structure",
    date: "2026-03-18",
    readTime: "11 min",
    thumbnail: CHART_1,
    content: {
      intro: "The most technically sound SMC setup will fail consistently if it's executed on the wrong broker. This is not a minor variable — it is foundational. A 2-pip spread on EUR/USD looks attractive until you realize the broker is requoting during the London open, widening spreads around news, and filling your limit orders 3 pips beyond your defined entry zone. The result is death by a thousand cuts: valid setups that never reach their first target because the execution infrastructure is working against you from the moment you click Buy. This article is a systematic framework for evaluating brokers specifically through the lens of SMC execution requirements.",
      htfAnalysis: "The SMC trader's primary execution demands are different from a trend-following swing trader or a scalper. You are entering at precise structural zones — fair value gaps, order blocks, sweep lows — where 1-2 pips of slippage can push an entry beyond the zone entirely, changing the risk/reward from 4R to 2R or invalidating the setup. You are also frequently holding through high-volatility news windows because those events often generate the displacement candles that confirm structural shifts. Your broker must be capable of handling both. The critical technical criteria are: raw spread on major pairs during London/NY overlap, execution type (STP vs. ECN vs. market maker), slippage rate on limit vs. market orders, and minimum stop distance.",
      intradayNarrative: "During the London session open — 08:00 GMT — most brokers widen spreads. The question is by how much and for how long. On EUR/USD, a well-capitalized ECN broker will widen from 0.1 pip to 0.3-0.5 pips for approximately 60-90 seconds. A market-maker broker may widen to 1.5-3 pips for 3-5 minutes. If your entry is a 4H FVG that spans 8 pips and you're entering on the London open, a 3-pip spread is consuming 37% of your entry zone before you've even placed the order. Broker selection must account for when you trade, not just the nominal spread on the broker's marketing page.",
      structuralConfirmation: "Three broker types exist on the retail side: Market Maker, STP (straight-through processing), and ECN (electronic communications network). For SMC execution, the hierarchy is clear: ECN > STP >> Market Maker. ECN brokers route orders directly to liquidity providers without a dealing desk intermediary. This means your stop at the sweep low is an actual resting order in the market, not a number on a broker's internal system. STP is acceptable. Market makers should be avoided for active structural trading because their incentive structure is misaligned with yours — they profit when you lose on the spread.",
      riskArchitecture: "The practical broker evaluation protocol: open a demo account and trade it identically to your live account for 10 sessions. Record the fill price vs. your intended price on every entry. Calculate average slippage. If average slippage on limit orders exceeds 1 pip on EUR/USD, the broker is suboptimal for SMC execution. Additionally, test during a news event — the London open or an NFP release. Observe spread behavior in real time. Many ECN brokers require a minimum deposit of $1,000-$5,000 to access raw spread accounts. At smaller account sizes, a reputable STP broker with consistent fills is preferable to a market maker with a $100 minimum.",
      lessons: "The broker decision is upstream of everything else. Before you refine your entry criteria, before you optimize your risk per trade, you need to know that your orders are being filled at the price you defined and that your stops are resting in the market, not sitting on a dealer's book. This matters most at the moment of maximum structural significance — the sweep low, the FVG fill, the BOS candle — which are precisely the moments when market-maker brokers have the most to gain from suboptimal fills. Treat broker selection as part of your structural risk architecture, not as a peripheral administrative decision."
    }
  },
  {
    slug: "order-block-vs-fair-value-gap",
    title: "Order Block vs. Fair Value Gap — Understanding the Structural Hierarchy",
    excerpt: "Traders frequently conflate order blocks and fair value gaps, treating them as equivalent signals. They are not. This breakdown clarifies what each concept represents, why one precedes the other structurally, and how to use them in the correct sequence.",
    category: "Structure",
    date: "2026-03-05",
    readTime: "9 min",
    thumbnail: CHART_2,
    content: {
      intro: "In SMC methodology, order blocks and fair value gaps are the two most referenced concepts — and the two most frequently misapplied. The misapplication stems from treating them as equivalent entry signals rather than understanding their structural relationship. An order block is a cause. A fair value gap is an effect. Getting the relationship right determines whether you're entering at the origin of institutional intent or chasing the residue of a move that already happened.",
      htfAnalysis: "An order block is the last opposing candle before a significant displacement. On the daily timeframe, it represents the final bearish candle before a strong bullish impulse (bullish OB) or the final bullish candle before a strong bearish impulse (bearish OB). The logic is institutional: a large participant needed to accumulate a position in the opposite direction without revealing their hand. That final candle is the footprint of their accumulation. The order block zone is where they were active, and price returns to that zone because there are unfilled orders remaining at those levels. The order block is the zone of origin.",
      intradayNarrative: "A fair value gap forms when price moves so rapidly through a price level that a gap appears between the high of one candle and the low of a candle two candles later — a three-candle sequence with the middle candle as the displacement. The gap represents an imbalance: buy-side and sell-side orders were not matched at that price level because price moved through it too quickly for market participants to respond. Price has a systematic tendency to return to these gaps to provide the opportunity for the orders that were missed. The FVG is the trace of the impulse, not the origin of it.",
      structuralConfirmation: "The structural hierarchy: the order block generates the impulse, and the impulse creates the FVG. They are co-located but not identical. A high-quality setup has an FVG that sits within or adjacent to an order block. When price returns to the FVG-within-OB zone, you have institutional-origin confluence: the same price level where accumulation occurred (OB) and where the rapid displacement left unfilled orders (FVG). An FVG without an upstream order block is lower quality — it tells you where the impulse left an imbalance but not necessarily where institutional intent originated.",
      riskArchitecture: "The practical application: on the 4H chart, identify the order block zone first. Note its range. Then identify FVGs on the 1H or 15M within that zone. Enter at the FVG — this gives you the precision. Define your stop below the order block's candle low — this gives you the structural invalidation point. The risk is defined by the OB; the entry is refined by the FVG. This is a significantly tighter stop than entering at the full OB zone, which improves your risk-to-reward ratio while maintaining structural validity.",
      lessons: "The order of operations matters: identify structural zones top-down (weekly to daily to 4H), locate order blocks at the relevant structural level, look for FVGs within those OB zones as precision entry vehicles, and size your risk relative to the OB invalidation point. Traders who enter at FVGs without first identifying the OB context will find inconsistent results — some FVGs are structurally significant, others are noise. The OB context is the filter that separates them."
    }
  },
  {
    slug: "cot-report-and-smc-alignment",
    title: "Using COT Report Positioning to Align Your SMC Bias",
    excerpt: "The Commitment of Traders report is a weekly window into institutional positioning. When COT data aligns with your SMC structure, you have macro confluence. When it diverges, you have a warning sign. Here is how to use it without overcomplicating your process.",
    category: "Macro",
    date: "2026-02-19",
    readTime: "10 min",
    thumbnail: CHART_3,
    content: {
      intro: "Most retail SMC traders operate entirely on price action without reference to the underlying positioning data that drives institutional order flow. The Commitment of Traders report, published weekly by the CFTC, reveals the net positioning of commercial hedgers, large speculators, and small speculators across futures markets. While the report has limitations — it is weekly and covers futures rather than spot FX — it provides a directional bias check that can significantly improve the quality of your SMC trade selection. Used correctly, it functions as a structural filter, not an entry signal.",
      htfAnalysis: "The COT report separates market participants into three categories. In FX futures, the category to focus on is Large Non-Commercial (large speculators/managed money). These are hedge funds and institutional traders positioning for directional moves. When large non-commercials are net long EUR/USD futures at an extreme reading — defined as the top or bottom 10% of the 3-year range — they have significant accumulated exposure in that direction. Strong trends in FX correlate with sustained large speculator positioning. Reversals often begin from extreme positioning readings.",
      intradayNarrative: "The practical workflow: every Friday after the 3:30 PM EST release, record the net positioning for EUR, GBP, JPY, and Gold. Compare this week's reading to the 52-week range. If EUR large speculator net longs are at a 52-week extreme, flag it for structural attention the following week. If large specs are heavily net long EUR and your SMC daily chart shows a bullish order block being approached, you have macro-to-micro alignment. If large specs are heavily net long EUR but your daily chart shows a bearish order block rejection forming, you have a divergence that warrants caution on aggressive long positioning.",
      structuralConfirmation: "The highest-quality COT signals are at extremes combined with reversal or continuation patterns. Net long extremes combined with a sweep of buy-side liquidity followed by structural shift signals a macro-confirmed reversal setup. Net short extremes combined with consistent structural breaks to the downside signals a macro-confirmed trend continuation. Mid-range positioning provides no signal — ignore it entirely. The COT report only adds value at the extremes. This is a weekly timeframe tool; it informs your daily bias, not your intraday entries.",
      riskArchitecture: "COT data does not change your risk per trade. It functions as a go/no-go filter on your structural bias. If COT positioning is aligned with your SMC setup, proceed with standard 0.5-1% risk allocation. If COT positioning is divergent from your SMC setup, reduce allocation by 50% or sit out entirely. The reasoning is probabilistic — you are stress-testing your existing thesis against an independent institutional data source. Trades that survive both the structural and positioning filter are the highest-conviction entries in the framework.",
      lessons: "The COT report will not make you a better intraday trader. It will make you a better weekly bias trader. The value is in filtering out trades that look structurally valid on the chart but are running against the institutional positioning tide. The FX market is too large and too institutionally dominated for retail technical analysis to work consistently in isolation. Adding one simple institutional data check — net positioning at extremes, aligned or divergent — is the minimum viable macro framework that any structural trader should maintain."
    }
  },
  {
    slug: "the-loss-that-changed-my-framework",
    title: "The Loss That Changed My Framework — On Revenge Trading and Structural Discipline",
    excerpt: "There was a week in 2022 where I gave back six weeks of gains in three days. The technical analysis was sound. The execution was not. This is an honest account of how psychological failure masquerades as analytical failure, and the structural response I built as a consequence.",
    category: "Psychology",
    date: "2026-02-03",
    readTime: "8 min",
    thumbnail: CHART_1,
    content: {
      intro: "In March 2022, EUR/USD broke through parity expectations early and I had a significant position in the right direction — short EUR/USD from a daily order block at 1.1050. The trade was working. Then the Fed released unexpectedly hawkish minutes and the position surged to 4R in a single session. I closed half. That was the last good decision I made that week. What followed was a sequence of trades that had nothing to do with the framework and everything to do with the emotional state I was in after a large win. This is not a story about how to trade. It is a story about what happens when you stop trading your system and start trading your feelings.",
      htfAnalysis: "The week after a large win is statistically one of the most dangerous periods for a discretionary trader. The literature on this is consistent across professional and retail cohorts. The mechanism is overconfidence bias compounded by increased risk appetite — you are, in psychological terms, playing with house money, which diminishes loss aversion. In behavioral economics this is the house money effect: people take larger risks with recent gains than with their baseline capital. For a trader, this manifests as wider stops, larger position sizes, entries outside the framework criteria, and an accelerating pace of trades. I did all four that week.",
      intradayNarrative: "By Wednesday of that week, I had taken five trades. Two were inside the framework. Three were not. The three that were not fit a recognizable psychological pattern: each was an attempt to catch up to the gains from the EUR/USD trade by finding equally large moves. The setups I chose had partial alignment — some structural basis — but were missing the full confluence the framework requires. The first of those three trades was a stop loss. The second was a stop loss. The third was the trade where I violated my daily risk limit and held a losing position overnight, which turned a 1% loss into a 3.5% loss by morning.",
      structuralConfirmation: "The psychological post-mortem revealed a consistent pattern: I was trading narrative, not structure. My internal monologue during those trades was about the size of the move I expected, not about the structural validity of the entry. EUR/USD moved 180 pips — GBP/USD must be setting up for something similar. That is a narrative. It has nothing to do with order blocks, liquidity sweeps, or structural shifts. It is a story I constructed after observing one large move, and I retrofitted structure onto it to justify the trade. This is one of the most dangerous forms of analytical failure because it is invisible in real time.",
      riskArchitecture: "The structural response I built after that week: a mandatory 24-hour cooling period after any trade that reaches 3R or above. The rule is simple — no new trades are permitted for 24 hours after a 3R+ close. The reasoning is not superstition; it is risk architecture. The 24 hours is designed to interrupt the emotional state that follows a large win before it can contaminate the next entry decision. Secondary rule: any week where I have exceeded my peak-to-trough drawdown limit triggers an automatic trading halt for the remainder of that week, regardless of how the remaining sessions look structurally.",
      lessons: "The framework did not fail that week. I failed the framework. The distinction matters because the corrective response is different. If the framework failed, you redesign it. If you failed the framework, you design structural controls that prevent the failure mode from occurring again. Revenge trading, overconfidence-driven position sizing, and narrative trading are not analytical problems — they are psychological problems with structural solutions. Rules that activate automatically under specific conditions are the structural equivalent of circuit breakers. They do not improve your analysis; they protect your capital from your own psychology during the periods when your psychology is most dangerous."
    }
  },
  {
    slug: "reading-liquidity-sweeps",
    title: "Reading Liquidity Sweeps — The Setup Before the Setup",
    excerpt: "A liquidity sweep is not an entry signal. It is a precondition. Treating it as an entry has destroyed more accounts than any other single misapplication of SMC methodology. This is the correct way to read sweeps within the broader structural sequence.",
    category: "Structure",
    date: "2026-01-20",
    readTime: "10 min",
    thumbnail: CHART_2,
    content: {
      intro: "The liquidity sweep is probably the most cited — and most misunderstood — concept in SMC trading communities. The typical retail interpretation: price sweeps a low, that is the entry. Long immediately. The result of this interpretation is a consistent pattern of entering into continuation moves disguised as reversals, catching falling knives on bearish displacement candles, and building a psychological association between sweeps and losses. The correct interpretation is more precise: a liquidity sweep confirms that a pool of resting orders has been triggered, and it creates the conditions necessary for a structural shift — but it is not the structural shift itself.",
      htfAnalysis: "Liquidity pools form where the market consensus expects price not to go. Below obvious swing lows, equal lows, and psychological levels, the market accumulates stop-loss orders from long positions and pending sell orders from breakout traders. These resting orders are the liquidity that large participants need to fill opposing positions. To buy a large position, institutional order flow requires a matching seller. The concentrated sell orders sitting below swing lows provide that supply. The sweep is the mechanism: price is pushed below the low to trigger those orders, fill the institutional buy interest, and then reverse. The sweep is not the reversal — it is the precondition that makes the reversal possible.",
      intradayNarrative: "The structural sequence is four steps: liquidity pool formation, sweep, displacement, structural shift. Most retail entries occur at step two. Correct entries occur at steps three and four. After the sweep, the displacement candle is the first evidence of institutional response — a strong, full-bodied candle moving away from the swept level. The displacement candle itself is still not an entry; it is the confirmation that the sweep attracted institutional interest. The structural shift — a break of structure on the lower timeframe that establishes a higher high in a bullish scenario — is the confirmation that direction has changed. Entry at the FVG left by the displacement candle, after structural shift, is the valid entry sequence.",
      structuralConfirmation: "The sweep validity criteria: First, the swept level must have been a clearly formed and respected liquidity pool with a minimum of two touches. A single-touch low is not a liquidity pool; it is a single data point. Second, the sweep must penetrate below the low with enough depth to reasonably trigger stops — typically 3-10 pips below the low for FX majors. A sweep that barely breaks the low by 1 pip may be incomplete. Third, the displacement candle following the sweep must be strong and directional, closing significantly away from the swept level. A weak candle after the sweep suggests indecision, not institutional absorption.",
      riskArchitecture: "Risk on post-sweep entries is defined by the swept level, not the displacement candle. Your stop goes below the sweep low for bullish setups — that is the structural invalidation point. If price returns below the sweep low, the setup is invalid. Entry at the FVG created by the displacement candle typically provides 2-3x the risk-to-reward of entering at the sweep itself, because the entry is tighter relative to the same stop point. On a setup with a 10-pip stop, entering at the FVG vs. the sweep reduces your risk per trade by 40-60% while maintaining the same invalidation structure.",
      lessons: "The sweep is the invitation, not the event. The market is showing you where liquidity was resting. Your job is to wait for confirmation that the institutional response to that sweep was directional and sustained. The waiting period between sweep and structural shift is where most traders fail — the urge to enter early is the same psychological pattern as all premature entries: the fear of missing the move. Train yourself to recognize that entering at the sweep, before displacement and structural shift, is not a different entry point; it is a structurally invalid entry dressed up as an early one."
    }
  }
];

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}

export function getArticlesByCategory(category: ArticleCategory): Article[] {
  return articles.filter((a) => a.category === category);
}
